### ISSUE TITLE
Question about NTRIP

### ISSUE THREAD

**Issue by ttmx** [jcmb/NTRIP#2]
Hey there! I'm trying to understand how to communicate manually with an external board I have, which receives RTCM.

https://github.com/jcmb/NTRIP/blob/b82918c659e3afbd4011fd12756520d0b298193d/NTRIP%20Client/NtripClient.py#L112

Your code has been a good part of my guidance. With this said, is there any chance you could explain to me why you're sending your coordinates back on the NTRIP socket? I'm still trying to wrap my head around the protocol, but the server I am using seems to work fine even if I do not send my coordinates back?

Is it from some sort of special setup you have?

Thank you!

**Comment by C4fishfood** [comment]
The location of the GPS rover (ntrip client) may be sent back to the caster in some cases such as where a virtual reference station (VRS) is used. This is more of function of how the caster is setup rather than the client- most publicly available casters will have a list of mount points and you get your RTCM string from whatever single one you select. There are some casters (which I believe are all marketed a paid/subscription plan) that will create a virtual station for your specific location by modeling a mesh between the physical mount points- so they would be interpolating between them in some way. The VRS is not really needed unless you are so far away from a physical mount point that the baseline distance is so great that your position error cannot be reduced enough for whatever you are trying to do.

**Comment by ttmx** [comment]
This was very useful.
I might eventually contribute my code if I am allowed to.
On this topic, is not having a license on purpose?

Thank you!

**Comment by jcmb** [comment]
As @C4fishfood points out the position is normally used for network RTK (VRS) there is also a class of caster which connects you to the closest base station without doing the mesh processing.

The other thing the the position gets used for is knowing where the rovers are for reporting. 

The source table has the field of NMEA required, when this is yes a client should send a position. 

if it is working don’t worry about it.

The code is based on the unavco ntrip code, which didn’t have a license that I noticed. I can go and ask them for the exact license if needed

**Comment by ttmx** [comment]
According to this website, it should be some unspecified version of the GPL.
https://software.rtcm-ntrip.org/export/HEAD/ntrip/trunk/BNC/src/bnchelp.html
Can you confirm I am looking at the wrong place?
Thank you!
